spring:
  application:
    name: metadata-service
  config:
    import: "optional:configserver:http://config-server:8888"
  cloud:
    config:
      username: ${CONFIG_SERVER_USERNAME:configuser}
      password: ${CONFIG_SERVER_PASSWORD:configpass}

debug: true

logging:
  level:
    org.flywaydb: DEBUG