#eureka:
#  client:
#    service-url:
#      defaultZone: http://eureka-server:8761/eureka/
#  instance:
#    prefer-ip-address: false
#    hostname: ${spring.application.name}
logging:
  level:
    root: INFO
    com.shin: DEBUG
    org.springframework.cloud: DEBUG