spring:
  application:
    name: metadata-service
  flyway:
    enabled: true
    schemas: metadata
    table: flyway_schema_history
    locations: classpath:db/migration/auth
    baseline-on-migrate: true
    validate-on-migrate: true
    out-of-order: false
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:5432/${POSTGRES_DB:shin}
    user: ${POSTGRES_USER:root}
    password: ${POSTGRES_PASSWORD:root}
api:
  version: "/api/v1"
