services:
  postgres:
    image: postgres:latest
    container_name: shin-postgres
    hostname: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    restart: unless-stopped
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres-data:/var/lib/postgresql
      - ./scripts/initialize-schemas:/docker-entrypoint-initdb.d
    networks:
      - shin-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:latest
    container_name: shin-redis
    hostname: redis
    command: redis-server --requirepass ${REDIS_PASSWORD}
    restart: always
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - redis-data:/data
    networks:
      - shin-network
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  eureka-server:
    build:
      context: .
      dockerfile: eureka-server/Dockerfile
    container_name: shin-eureka
    hostname: eureka-server
    ports:
      - "${EUREKA_PORT}:8761"
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
      - EUREKA_USERNAME=${EUREKA_USERNAME}
      - EUREKA_PASSWORD=${EUREKA_PASSWORD}
    networks:
      - shin-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8761/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

  config-server:
    build:
      context: .
      dockerfile: config-server/Dockerfile
    container_name: shin-config
    hostname: config-server
    ports:
      - "${CONFIG_SERVER_PORT}:8888"
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE},native
      - CONFIG_SERVER_ENCRYPT_KEY=${CONFIG_SERVER_ENCRYPT_KEY}
      - CONFIG_SERVER_USERNAME=${CONFIG_SERVER_USERNAME}
      - CONFIG_SERVER_PASSWORD=${CONFIG_SERVER_PASSWORD}
    volumes:
      - ./config-repo:/app/config-repo
    depends_on:
      eureka-server:
        condition: service_healthy
    networks:
      - shin-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8888/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

  gateway:
    build:
      context: .
      dockerfile: gateway/Dockerfile
    container_name: shin-gateway
    hostname: gateway
    ports:
      - "${GATEWAY_PORT}:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
      - CONFIG_SERVER_USERNAME=${CONFIG_SERVER_USERNAME}
      - CONFIG_SERVER_PASSWORD=${CONFIG_SERVER_PASSWORD}
    depends_on:
      eureka-server:
        condition: service_healthy
      config-server:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - shin-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 90s
#
#  metadata:
#    build:
#      context: ./metadata
#      dockerfile: Dockerfile
#    container_name: shin-metadata
#    hostname: metadata-service
#    environment:
#      - SPRING_PROFILES_ACTIVE=dev
#      - CONFIG_SERVER_USERNAME=configuser
#      - CONFIG_SERVER_PASSWORD=configpass
#    depends_on:
#      eureka-server:
#        condition: service_healthy
#      config-server:
#        condition: service_healthy
#      postgres:
#        condition: service_healthy
#    networks:
#      - shin-network
#    healthcheck:
#      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8081/actuator/health"]
#      interval: 30s
#      timeout: 10s
#      retries: 5
#      start_period: 90s
#
#  upload:
#    build:
#      context: ./upload
#      dockerfile: Dockerfile
#    container_name: shin-upload
#    hostname: upload-service
#    environment:
#      - SPRING_PROFILES_ACTIVE=dev
#      - CONFIG_SERVER_USERNAME=configuser
#      - CONFIG_SERVER_PASSWORD=configpass
#    depends_on:
#      eureka-server:
#        condition: service_healthy
#      config-server:
#        condition: service_healthy
#      postgres:
#        condition: service_healthy
#      redis:
#        condition: service_healthy
#    networks:
#      - shin-network
#    healthcheck:
#      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8082/actuator/health"]
#      interval: 30s
#      timeout: 10s
#      retries: 5
#      start_period: 90s

  encoding:
    build:
      context: ./encoding
      dockerfile: Dockerfile
    container_name: shin-encoding
    hostname: encoding-service
    environment:
      DECODE_JOB_QUEUE_URL: ${DECODE_JOB_QUEUE_URL}
      ENCODE_FINISHED_TOPIC_ARN: ${ENCODE_FINISHED_TOPIC_ARN}
      CHUNK_PROCESSED_TOPIC_ARN: ${CHUNK_PROCESSED_TOPIC_ARN}
      RAW_BUCKET_NAME: ${RAW_BUCKET_NAME}
      PROCESSED_BUCKET_NAME: ${PROCESSED_BUCKET_NAME}
      AWS_REGION: ${AWS_REGION}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_SESSION_TOKEN: ${AWS_SESSION_TOKEN:-}
    networks:
      - shin-network

  thumbnail:
    build:
      context: ./thumbnail
      dockerfile: Dockerfile
    container_name: shin-thumbnail
    hostname: thumbnail-service
    environment:
      THUMBNAIL_JOB_QUEUE_URL: ${THUMBNAIL_JOB_QUEUE_URL}
      RAW_BUCKET_NAME: ${RAW_BUCKET_NAME}
      THUMBNAIL_BUCKET_NAME: ${THUMBNAIL_BUCKET_NAME}
      AWS_REGION: ${AWS_REGION}
      THUMBNAIL_GENERATED_TOPIC_ARN: ${THUMBNAIL_GENERATED_TOPIC_ARN}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_SESSION_TOKEN: ${AWS_SESSION_TOKEN:-}
    networks:
      - shin-network


networks:
  shin-network:
    driver: bridge

volumes:
  postgres-data:
  redis-data:
