spring:
  application:
    name: interaction-service
  config:
    import: "optional:configserver:http://localhost:8888"
  cloud:
    config:
      username: ${CONFIG_SERVER_USERNAME:configuser}
      password: ${CONFIG_SERVER_PASSWORD:configpass}
  data:
    redis:
      host: localhost
      port: 6379
      password: redis
      client-type: lettuce
      lettuce:
        pool:
          enabled: true
logging:
  level:
    org.flywaydb: DEBUG